import OpenApiCreateClient from 'openapi-fetch'

/**
 * Creates an instance of the OpenAPI client.
 *
 * @returns {ReturnType<typeof OpenApiCreateClient>} - The configured OpenAPI client.
 * @example
 * import type { paths } from "./openapi.d.ts" // Types generated by `buildSchema` function from `@backan/builder`
 * 
 * // create client
 * const client = createClient<paths>( {
 *   baseUrl : 'http://localhost:1312/',
 * } )
 * 
 * // example of call
 * const response = await client.GET( '/random/child', {
 *   params : { query : { value : 'myValue', }, },
 * } )
 * 
 * console.log( response ) 
 */
export const createClient = OpenApiCreateClient
